Introduce default job length of 10 minutes
voxpupuli/modulesync_config pull request #692
Opened 2020-12-14 16:20 UTC by traylenator

Override default job timeout for Github actions.

Set the job timeout to 10 minutes rather than the default
360 minutes (6 hours)

Running some test jobs with 1 minute the queued time per job does not
appear to count to the limit which is desirable.

Job timeout can be overridden in `.sync.yml`.

https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

2020-12-14 16:21 UTC, traylenator commented
I'm sure other folk have a better real world idea of what the default limit should be.

2020-12-14 17:14 UTC, ekohl requested changes
I think tests often need more than 10 minutes. This feels way too aggressive to me and something we would need to modify on most repositories. I'd start with 30, 45 or 60 minutes by default.

I also wonder if we can query run times for our actions to make a more informed decision.

2020-12-14 18:42 UTC, traylenator commented
Start at 60 minutes and reduce by 10 each modulesync release till it becomes too painful.

I did have a quick look.

There's this 

https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#get-workflow-run-usage

2020-12-14 18:50 UTC, bastelfreak commented
https://github.com/voxpupuli/puppet-collectd/actions/runs/383544865 collectd for example took 16min to run and we've many more that take more than 10min.

2020-12-15 07:33 UTC, traylenator commented
```bash
curl \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/voxpupuli/puppet-nftables/actions/runs/1549477914/timing 
```

is not available, I think its only available for billable time in private repos.

2020-12-15 07:36 UTC, traylenator commented
> https://github.com/voxpupuli/puppet-collectd/actions/runs/383544865 collectd for example took 16min to run and we've many more that take more than 10min.

For that collected its the 12 minute Debian puppet 6 job (the slowest) that is significant rather than the total 16 minutes.

But sure push up the time.

2020-12-15 09:54 UTC, bastelfreak approved these changes

2020-12-15 16:06 UTC, ekohl approved these changes
I would be ok with 40 minutes as a first value.

2021-02-23 14:03 UTC, merged