update CONTRIBUTING.md for beaker testing
voxpupuli/modulesync_config pull request #702
Opened 2021-02-28 00:12 UTC by bastelfreak

2021-03-01 09:12 UTC, kenyon approved these changes

2021-03-01 09:22 UTC, ekohl requested changes

2021-03-01 09:22 UTC, ekohl commented on moduleroot/.github/CONTRIBUTING.md.erb
> +BEAKER_PUPPET_COLLECTION=puppet7 BEAKER_setfile=debian10-64{hypervisor=docker} BEAKER_destroy=yes bundle exec rake beaker
You can leave of `BEAKER_PUPPET_COLLECTION` as well, there's a default:
https://github.com/voxpupuli/voxpupuli-acceptance/blob/ddcf483eef69f629c6d530d318985726eadd82d2/lib/voxpupuli/acceptance/spec_helper_acceptance.rb#L30

We also default to the docker hypervisor:
https://github.com/voxpupuli/voxpupuli-acceptance/blob/ddcf483eef69f629c6d530d318985726eadd82d2/lib/voxpupuli/acceptance/spec_helper_acceptance.rb#L32

I also think `BEAKER_destroy=yes` is the default behavior:

So it can be
```suggestion
BEAKER_setfile=debian10-64 bundle exec rake beaker
```

Btw, a bit above we also have instructions `bundle exec rake beaker:centos-7-x64` and `bundle exec rake beaker:ssh:centos-7-x64` but those don't work for us since we don't store the yaml files in our repos. This whole section needs a bit of a rewrite.

Perhaps we should refer to https://github.com/voxpupuli/voxpupuli-acceptance#readme or https://github.com/voxpupuli/voxpupuli-acceptance#running-tests for more information on how to run beaker.

2021-03-01 10:58 UTC, ekohl commented on moduleroot/.github/CONTRIBUTING.md.erb
> +BEAKER_PUPPET_COLLECTION=puppet7 BEAKER_setfile=debian10-64{hypervisor=docker} BEAKER_destroy=yes bundle exec rake beaker
I opened https://github.com/voxpupuli/modulesync_config/pull/703 and https://github.com/voxpupuli/voxpupuli-acceptance/pull/17 with what I think is the best path forward. Please have a look.

2021-07-13 16:34 UTC, ekohl commented
Can you rebase this? Or can it be closed?

2021-07-13 19:18 UTC, closed without merging