Relase 4.3.0
voxpupuli/modulesync_config pull request #750
Opened 2021-10-02 11:36 UTC by bastelfreak

2021-10-02 11:55 UTC, bjoernhaeuser approved these changes

2021-10-03 00:20 UTC, smortex requested changes
CHANGELOG.md seems to be missing.  I think we do not just update the README :wink:

2021-10-03 15:48 UTC, bastelfreak commented
@smortex ah sorry, fixed it

2021-10-03 19:17 UTC, smortex approved these changes
LGTM!

2021-10-04 10:27 UTC, ekohl approved these changes

2021-10-31 10:29 UTC, alexjfisher approved these changes

2021-10-31 10:37 UTC, merged