Dont manage .rspec_parallel anymore
voxpupuli/modulesync_config pull request #895
Opened 2024-05-09 15:34 UTC by bastelfreak

requires https://github.com/puppetlabs/puppetlabs_spec_helper/pull/451 since https://github.com/puppetlabs/puppetlabs_spec_helper/pull/446 the rake task configures the output so we don't need .rspec_parallel anymore.

2024-05-09 15:57 UTC, TheMeier approved these changes

2024-05-10 09:36 UTC, ekohl requested changes
Can we somehow ensure `puppetlabs_spec_helper` is new enough to include the changes?

2024-05-10 09:49 UTC, bastelfreak commented
Yes. I will update voxpupuli-test to depend on the latest PSH as soon as it's released. Then we can depend on the newest voxpupuli-test in modulesync_config.

2024-05-23 15:59 UTC, ekohl approved these changes

2024-05-23 16:06 UTC, merged