Support fact stringyfication
voxpupuli/modulesync_config pull request #908
Opened 2024-06-14 14:19 UTC by bastelfreak

FacterDB/rspec-puppet-facts have an option switch the symbolized first-level keys in a factset to strings (all following/nested keys are always strings). This PR makes this configuration opt-in so we can switch over modules from symbols to strings in their spec files.

2024-06-14 14:23 UTC, bastelfreak commented
Tested at https://github.com/voxpupuli/puppet-allknowingdns/pull/64

2024-06-15 12:03 UTC, ekohl requested changes

2024-06-15 12:16 UTC, bastelfreak commented on moduleroot/spec/spec_helper.rb.erb
> +<%- if @configs['facterdb_string_keys'] -%>
that's why I added a default to config_defaults.yml. But I can remove the if condition here if you like.

2024-06-15 12:26 UTC, bastelfreak commented
verified again at https://github.com/voxpupuli/puppet-allknowingdns/pull/64/commits

2024-06-15 12:34 UTC, ekohl commented on moduleroot/spec/spec_helper.rb.erb
> +<%- if @configs['facterdb_string_keys'] -%>
but the default is `false`. If you want it unconditionally, you should check for `.nil?`

2024-06-15 12:39 UTC, ekohl commented on moduleroot/spec/spec_helper.rb.erb
> +<%- if @configs['hiera_config'] || @configs['mock_with'] || @configs['facterdb_string_keys'] -%>
The configure block should be there unconditionally now
```suggestion
```

2024-06-15 12:39 UTC, ekohl commented on moduleroot/spec/spec_helper.rb.erb
>  <%- end -%>
And then drop this too
```suggestion
```

2024-06-15 13:11 UTC, bastelfreak commented on moduleroot/spec/spec_helper.rb.erb
> +<%- if @configs['facterdb_string_keys'] -%>
I'm not sure if I can follow your thoughts. My idea was to always add the `facterdb_string_keys` option with a default of `false` and individual modules can switch to `true`. And if we ever want to, we can set it to `true` in `voxpupuli-test` or `rspec-puppet-facts` and that works with the current code. Did you have something else in mind?

2024-06-15 15:05 UTC, ekohl approved these changes

2024-06-15 15:05 UTC, ekohl commented on moduleroot/spec/spec_helper.rb.erb
> +  c.facterdb_string_keys = <%= @configs['facterdb_string_keys'] %>
Would it make sense to keep the list sorted alphabetically?

2024-06-15 15:48 UTC, bastelfreak commented on moduleroot/spec/spec_helper.rb.erb
> +  c.facterdb_string_keys = <%= @configs['facterdb_string_keys'] %>
done

2024-06-15 15:51 UTC, merged